#!/usr/bin/env python3
"""Bundle your PocketStation BIOS and memory cards into psdata.cpp for the Meshtastic module.

    python3 pack.py OUTPUT_DIR [--bios FILE] [--cards DIR]

OUTPUT_DIR is the module folder inside the firmware source, for example
    ~/meshtastic-firmware/src/modules/optional/PocketStation
By default the BIOS and cards are taken from ../esp32/data (the same ones the CoreS3 build uses).

psdata.cpp contains your BIOS and games. Keep it on your own machine: never commit or share it.
"""
import argparse
import binascii
import os
import struct
import sys

CARD = 0x20000
BLOCK = 0x2000
BIOS = 0x4000


def read_card(path):
    data = open(path, "rb").read()
    extra = len(data) - CARD  # .gme and .mem files carry a header before the raw card
    if extra not in (0, 64, 3904):
        raise ValueError("not a memory card image (unexpected size %d)" % len(data))
    data = data[extra:]
    if data[:2] != b"MC":
        raise ValueError("not a memory card image (no MC signature)")
    return data


def has_pocketstation_game(card):
    for i in range(1, 16):
        frame = card[i * 128:(i + 1) * 128]
        head = card[i * BLOCK:i * BLOCK + 0x100]
        if frame[0] == 0x51 and head[:2] == b"SC" and head[0x52:0x55] == b"MCX":
            return True
    return False


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    default_data = os.path.join(here, "..", "esp32", "data")
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("output_dir")
    ap.add_argument("--bios", default=os.path.join(default_data, "bios.bin"))
    ap.add_argument("--cards", default=os.path.join(default_data, "cards"))
    args = ap.parse_args()

    out_dir = os.path.expanduser(args.output_dir)
    if not os.path.isdir(out_dir):
        sys.exit("Output folder not found: %s\nCopy the PocketStation module folder into the firmware first." % out_dir)

    bios = open(args.bios, "rb").read()
    if len(bios) != BIOS:
        sys.exit("%s is %d bytes; a PocketStation BIOS dump is %d bytes." % (args.bios, len(bios), BIOS))

    blocks = []  # unique 8 KiB blocks
    index = {}
    table = b""
    count = 0
    names = sorted(n for n in os.listdir(args.cards) if n.lower().endswith((".mcd", ".mcr", ".mc", ".srm", ".gme", ".mem", ".ps", ".bin")))
    for name in names:
        try:
            card = read_card(os.path.join(args.cards, name))
        except ValueError as e:
            print("  skipped %s: %s" % (name, e))
            continue
        if not has_pocketstation_game(card):
            print("  skipped %s: no PocketStation game on it" % name)
            continue
        refs = []
        for i in range(16):
            b = card[i * BLOCK:(i + 1) * BLOCK]
            if b not in index:
                index[b] = len(blocks)
                blocks.append(b)
            refs.append(index[b])
        title = os.path.splitext(name)[0].encode("ascii", "replace")[:31]
        table += struct.pack("<32sI16H", title, binascii.crc32(card) & 0xFFFFFFFF, *refs)
        count += 1
        print("  %s" % name)
    if not count:
        sys.exit("No PocketStation games found in %s" % args.cards)
    if count > 64:
        sys.exit("Too many cards (%d); the limit is 64." % count)

    header_len = 24
    bios_off = header_len + len(table)
    blocks_off = bios_off + BIOS
    pack = struct.pack("<4sIIIII", b"PSPK", 1, count, len(blocks), bios_off, blocks_off) + table + bios + b"".join(blocks)

    out_path = os.path.join(out_dir, "psdata.cpp")
    with open(out_path, "w") as f:
        f.write("// Generated by pack.py. Contains your PocketStation BIOS and games: do not commit or share.\n")
        f.write("#include <stdint.h>\n\n")
        f.write('extern "C" {\n')
        f.write("extern const uint32_t psdata_len;\n")
        f.write("extern const uint8_t psdata[] __attribute__((aligned(4)));\n")
        f.write("const uint32_t psdata_len = %d;\n" % len(pack))
        f.write("const uint8_t psdata[] = {\n")
        for i in range(0, len(pack), 32):
            f.write(",".join(str(b) for b in pack[i:i + 32]) + ",\n")
        f.write("};\n}\n")
    print("%d cards, %d KB of firmware space -> %s" % (count, len(pack) // 1024, out_path))


if __name__ == "__main__":
    main()
